# 7. 知っておきたい回避策

Rustの非同期サポートは、まだかなり新しく、要求の高い便利な機能がまだ開発中であり、いくつかの診断機能も標準以下です。
このチャプターはいくつか一般的な問題を議論して、それらを回避する方法を説明します。

## 7.1. `async`ブロック内の`?`

ちょうど`async fn`のように、`async`ブロック内で`?`を使用することは一般的です。
しかし、`async`ブロックのリターン型は明示的に記述されていません。
これはコンパイラが`async`ブロックのエラー型の推測に失敗する原因になる可能性があります。

例えば、次のコードは、次のエラーを出します。

```rust
let fut = async {
    boo().await?;
    bar().await?;

    Ok(())
};
```

```text
error[E0282]: type annotations needed
 --> src/main.rs:5:9
  |
4 |     let fut = async {
  |         --- consider giving `fut` a type
5 |         foo().await?;
  |         ^^^^^^^^^^^^ cannot infer type
```

残念ながら、現在「`fut`の型を与える」方法も、`async`ブロックのリターン型を明示的に記述する方法もありません。
これを回避するために、`async`ブロックの成功とエラー型を提供するために「ターボ・フィッシュ」演算子を使用します。

```rust
let fut = async {
    foo().await?;
    bar().await?;

    Ok::<(), MyError>(())       // これは明示的な型注釈であることに注意してください。
}
```

## 7.2. 概算(approximate)の送信

いくつかの`async fn`状態マシンは、スレッド間で安全に送信される一方で、そのほかはそうではありません。
`async fn`または`Future`が`Send`であるかは、非`Send`型が`.await`ポイントを超えて保持されているかどうかによって決まります。
`.await`ポイントを超えて保持されるかもしれない値を、コンパイラはその最善の概算をしますが、現在多くの場所でこの分析は保守的すぎます。

例えば、単純な非`Send`型、おろらく`Rc`を含む型を考えてみましょう。

```rust
use std::rc::Rc;

#[derive(Default)]
struct NotSend(Rc<()>);
```

`NotSend`型の変数は、`async fn`によって返される結果の`Future`型が`Send`でなければならないとき、`async fn`内で一時的に簡単に現れます。

```rust
async fn bar() {}
async fn foo() {
    NotSend::default();
    bar().await;
}

fn require_send(_: impl Send) {}

fn main() {
    require_send(foo());
}
```

しかし、もし変数に`NotSend`を保存するように`foo`を変更した場合、もはやこの例はコンパイルされません。

```rust
async fn foo() {
    let x = NotSend::default();     // 非`Send`値を変数`x`に保存する。
    bar().await;
}   // 変数`x`はここでドロップされる。非`Send`値が`.await`ポイントを超えて存在するため、エラーが発生する。。
// よって、関数`foo`が`Send`でなくなる。
```

```text
error[E0277]: `std::rc::Rc<()>` cannot be sent between threads safely
  --> src/main.rs:15:5
   |
15 |     require_send(foo());
   |     ^^^^^^^^^^^^ `std::rc::Rc<()>` cannot be sent between threads safely
   |
   = help: within `impl std::future::Future`, the trait `std::marker::Send` is not implemented for `std::rc::Rc<()>`
   = note: required because it appears within the type `NotSend`
   = note: required because it appears within the type `{NotSend, impl std::future::Future, ()}`
   = note: required because it appears within the type `[static generator@src/main.rs:7:16: 10:2 {NotSend, impl std::future::Future, ()}]`
   = note: required because it appears within the type `std::future::GenFuture<[static generator@src/main.rs:7:16: 10:2 {NotSend, impl std::future::Future, ()}]>`
   = note: required because it appears within the type `impl std::future::Future`
   = note: required because it appears within the type `impl std::future::Future`
note: required by `require_send`
  --> src/main.rs:12:1
   |
12 | fn require_send(_: impl Send) {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

このエラーは正解です。
もし、`x`を変数内に保存した場合、それは`.await`の後までドロップされず、そのポイントで`async fn`は異なるスレッドで動作させられるかもしれません。
`Rc`は`Send`でないため、それをスレッド間で移動することを許すことは健全ではありません。
これの1つの簡単な解決策は、`.await`の前で`Rc`をドロップすることですが、残念ながら現在では機能しません。

この問題の周りを成功裡に機能させるtめに、任意の非`Send`変数をカプセルするブロック・スコープを導入する必要があるかもしれません。
これは、これらの値が`.await`ポイントを超えて生存しないことをコンパイラに簡単に伝えます。

```rust
async fn foo() {
    {
        let x = NotSend::default();
    }   // ここで`x`がドロップされて、`.await`ポイントを超えて非`Send`値が存在しなくなる。
    bar().await;
}
```

## 7.3. 再帰

内部的に、`async fn`は、それぞれ`.await`されるサブ`Future`を含む、状態マシン型を作成します。
これは、結果として得られる状態マシン型が、それ自身を含む必要があるため、再帰`async fn`をすこし難しくします。

```rust
// この関数は・・・
async fn foo() {
    step_one().await;
    step_two().await;
}
// 次のような状態マシン型を作成します。
enum Foo {
    First(StepOne),
    Second(StepTwo),
}

// よって、この関数は・・・
async fn recursive() {
    recursive().await;
    recursive().await;
}
// 次のような状態マシン型を作成します。
Enum Recursive {
    First(Recursive),
    Second(Recursive),
}
```

これは機能しません -- 無限サイズな型を作成しました!
コンパイラは不平を言います。

```text
error[E0733]: recursion in an `async fn` requires boxing
 --> src/lib.rs:1:22
  |
1 | async fn recursive() {
  |                      ^ an `async fn` cannot invoke itself directly
  |
  = note: a recursive `async fn` must be rewritten to return a boxed future.
```

これを許可するために、`Bx`を使用した間接化を導入する必要があります。
残念ながら、コンパイラの制限は、`Box::pin`で`recursive()`への呼び出しを単に包むだけでは十分でないことを意味します。
これを機能させるために、`async`ブロックを`.boxed()`を返す非`async`関数内に`recursive`を入れる必要があります。

```rust
use futures::future::{BoxFuture, FutureExt};

fn recursive() -> BoxFuture<'static, ()> {
    async move {
        recursive().await;
        recursive().await;
    }.boxed()
}
```

## 7.4. トレイト内の`async`

現在、`async fn`は、安定版リリースでトレイト内で使用できません。
2022年11月17日から、トレイト内の非同期関数のMVP(Minimum Viable Product: 価値を提供できる最小のプロダクト)が、コンパイラ・ツール・チェインのナイトリー・バーションで利用できます。
詳細は[ここ](https://blog.rust-lang.org/inside-rust/2022/11/17/async-fn-in-trait-nightly.html)を参照してください。

それまでの間、安定したツール・チェーンのために、[crates.io](https://crates.io/)の[async-trait](https://crates.io/crates/async-trait)クレートを使用した回避策があります。

これらのトレイト・メソッドを使用すると、関数呼び出しごとにヒープが割り当てられることに注意してください。
これは、大部分のアプリケーションにとって大きなコストではありませんが、1秒間に何百万回も呼び出されることが予想される低レベルな関数の公開APIで、この機能を使用するか決定するときは、検討されるべきです。
